Repository letsdrink/ouzo, pull requests merged in 2023-06, with the labels that each got.

#302 Implemented PHP 8.2 support
  .github/workflows/build.yaml
  CHANGELOG.md
  Dockerfile-dev
  README.md
  composer.json
  composer.lock
  src/Ouzo/Core/Csrf/CsrfProtector.php
  src/Ouzo/Core/Db/Stats.php
  src/Ouzo/Core/Helper/FormHelper.php
  src/Ouzo/Core/Helper/HtmlElementRenderer.php
  src/Ouzo/Core/Middleware/Interceptor/DefaultRequestId.php
  src/Ouzo/Core/Model.php
  src/Ouzo/Core/Request/RequestContext.php
  src/Ouzo/Core/Uri.php
  src/Ouzo/Core/Uri/Es6GeneratorTemplates.php
  src/Ouzo/Core/View/PhtmlRenderer.php
  src/Ouzo/Goodies/Utilities/Clock.php
  src/Ouzo/Goodies/Utilities/DynamicProxy.php
  src/Ouzo/Goodies/Utilities/Functions.php
  src/Ouzo/Goodies/Utilities/Iterator/FilteringIterator.php
  src/Ouzo/Goodies/Utilities/Strings.php
  test/src/Ouzo/Core/FrontControllerTest.php
  test/src/Ouzo/Core/ModelTest.php
  test/src/Ouzo/Core/SampleMiddleware.php
  test/src/Ouzo/Goodies/Utilities/PathTest.php
  test/src/Ouzo/Goodies/Utilities/StringsTest.php
Labels: feature

#303 Add attributes to Layout
  src/Ouzo/Core/Layout.php
Labels: enhancement

#304 Fix htmlspecialchars null string
  src/Ouzo/Core/Helper/FormHelper.php
Labels: bug

#306 Bump twig
  src/Ouzo/Core/View/OuzoTwigExtension.php
  src/Ouzo/Core/View/TwigInitializer.php
  src/Ouzo/Core/View/TwigRenderer.php
Labels: enhancement

#307 Ignore deprecated warnings in default error handler.
  src/Ouzo/Core/ExceptionHandling/ErrorHandler.php
Labels: enhancement

#308 Fix loading twig template
  src/Ouzo/Core/View/TwigRenderer.php
Labels: bug

#309 Added support for count query with DISTINCT support.
  CHANGELOG.md
  src/Ouzo/Core/Db/Dialect/Dialect.php
  src/Ouzo/Core/Db/Dialect/MySqlDialect.php
  src/Ouzo/Core/Db/Dialect/PostgresDialect.php
  src/Ouzo/Core/Db/Dialect/Sqlite3Dialect.php
  test/src/Ouzo/Core/Db/Dialect/PostgresDialectTest.php
  test/src/Ouzo/Core/Tools/Model/Template/GeneratorTest.php
Labels: enhancement

#310 Fix generating routes
  src/Ouzo/Core/Uri/UriGeneratorTemplates.php
Labels: bug

#311 Handle mocking readonly class
  src/Ouzo/Goodies/Utilities/DynamicProxy.php
  test/src/Ouzo/Goodies/Utilities/DynamicProxyClassesFor71.php
  test/src/Ouzo/Goodies/Utilities/DynamicProxyTest.php
Labels: enhancement

#312 Replaced EMPTY_STRING with EMPTY.
  CHANGELOG.md
  src/Ouzo/Core/Db/Dialect/Dialect.php
  src/Ouzo/Core/Helper/FormHelper.php
  src/Ouzo/Core/Helper/HtmlElementRenderer.php
  src/Ouzo/Core/Uri/UriGeneratorTemplates.php
  src/Ouzo/Goodies/Utilities/DynamicProxy.php
  src/Ouzo/Goodies/Utilities/Strings.php
  src/Ouzo/Goodies/Utilities/ToString/SimpleToStringStyle.php
Labels: enhancement

#313 Fix StrSubstitutor for php 8.2
  src/Ouzo/Goodies/Utilities/StrSubstitutor.php
Labels: bug

#314 Strings::sprintAssoc should treat null and empty string the same
  src/Ouzo/Goodies/Utilities/Strings.php
  test/src/Ouzo/Goodies/Utilities/StringsTest.php
Labels: bug
