Repository letsdrink/ouzo, pull requests merged in 2024-10, with the labels that each got.

#323 Add an option to truncate bound values
  src/Ouzo/Core/Db/StatementExecutor.php
Labels: feature

#324 Removed passing params for logger methods in order to make it PSR-3 compatible.
  src/Ouzo/Core/Db/StatementExecutor.php
  src/Ouzo/Core/Middleware/Interceptor/LogRequest.php
Labels: bug

#325 Refactored logger, so that we expose our own adapter.
  src/Ouzo/Core/Logger/AbstractOuzoLogger.php
  src/Ouzo/Core/Logger/ContextEnhancer.php
  src/Ouzo/Core/Logger/Logger.php
  src/Ouzo/Core/Logger/LoggerAdapter.php
  src/Ouzo/Core/Logger/StdOutputLogger.php
  src/Ouzo/Core/Logger/SyslogLogger.php
  test/src/Ouzo/Core/Logger/LoggerAdapterTest.php
  test/src/Ouzo/Core/Logger/SyslogLoggerTest.php
Labels: enhancement
